import { Project } from "@/types/common";

export const projects: Project[] = [
  {
    id: "ai-learning-platform",
    slug: "ai-learning-platform",
    title: "AI Adaptive Learning Platform",
    subtitle: "Emotion-Aware Personalized Learning Analytics using Deep Learning",
    category: "ai",
    problem:
    "Traditional e-learning platforms cannot understand whether learners are engaged, confused, or distracted, resulting in ineffective learning experiences and high dropout rates.",
    solution:
    "Developed an AI-powered adaptive learning platform that analyzes learner emotions in real time using computer vision and deep learning. The platform provides personalized learning insights and engagement analytics to improve learning outcomes.",
    features: [
      "Real-time emotion detection using Computer Vision & Deep Learning",
      "Learner engagement analysis and attention tracking",
      "Personalized learning insights and recommendations",
      "AI-powered emotion classification (engaged, confused, distracted)",
      "Interactive analytics dashboard with visual reports",
      "Responsive web interface optimized for all devices",
    ],
    architecture:
    "React Frontend → Django Backend → TensorFlow Deep Learning Model → OpenCV + MediaPipe → Learning Analytics Dashboard",
    techStack: [
      { name: "React", icon: "FaReact", category: "Frontend" },
      { name: "Django", icon: "SiDjango", category: "Backend" },
      { name: "Python", icon: "FaPython", category: "Language" },
      { name: "TensorFlow", icon: "SiTensorflow", category: "AI/ML" },
      { name: "OpenCV", icon: "SiOpencv", category: "Computer Vision" },
      { name: "MediaPipe", icon: "SiMediapipe", category: "Computer Vision" },
      { name: "JavaScript", icon: "FaJs", category: "Language" },
      { name: "HTML", icon: "FaHtml5", category: "Frontend" },
      { name: "CSS", icon: "FaCss3", category: "Frontend" },
    ],
    screenshots: ["/images/projects/ai-learning-platform/hero.png"],
    demoVideo: "",
    github: "https://github.com/harii-ram/SRM-",
    liveDemo: "",
    duration: "3 Months",
    teamSize: "Team Project",
    role: "Developed AI modules, integrated frontend and backend, implemented emotion detection, participated in model training, testing, and deployment.",
    challenges: [
      "Real-time emotion recognition with high accuracy",
      "Improving model accuracy across diverse demographics",
      "Optimizing AI inference performance for real-time processing",
    ],
    achievements: [
      "Successfully developed a complete AI-driven adaptive learning platform",
      "Achieved reliable real-time engagement analysis",
      "Integrated end-to-end learning analytics",
    ],
    futureScope: [
      "Voice emotion analysis integration",
      "AI Tutor integration for personalized guidance",
      "Personalized learning path recommendations",
      "Cloud deployment for scalability",
    ],
    awards: ["🥇 First Prize — NOOB HACKFEST 2026 (₹25,000)"],
    featured: true,
    year: 2026,
  },
  {
    id: "driver-drowsiness",
    slug: "driver-drowsiness",
    title: "Driver Drowsiness Detection System",
    subtitle: "AI-Based Real-Time Driver Fatigue Monitoring System",
    category: "ai",
    problem:
    "Driver fatigue is one of the major causes of road accidents due to delayed reaction times and reduced alertness, especially during long-distance travel.",
    solution:
    "Developed an AI-powered driver monitoring system that detects signs of drowsiness using computer vision and alerts the driver in real time to prevent accidents.",
    features: [
      "Real-time eye blink detection and monitoring",
      "Face tracking and facial landmark detection",
      "Fatigue detection with instant audio alerts",
      "Live webcam processing at 30+ FPS",
      "Safety monitoring dashboard with real-time status",
      "Low-light operation capability",
    ],
    architecture: "Camera → OpenCV → AI Detection Model → Alert System → Driver",
    techStack: [
      { name: "Python", icon: "FaPython", category: "Language" },
      { name: "OpenCV", icon: "SiOpencv", category: "Computer Vision" },
      { name: "TensorFlow", icon: "SiTensorflow", category: "AI/ML" },
      { name: "NumPy", icon: "SiNumpy", category: "Library" },
    ],
    screenshots: ["/images/projects/driver-drowsiness/hero.png"],
    demoVideo: "",
    github: "https://github.com/Nithish264033/Drowsy_Detection",
    liveDemo: "",
    duration: "1 Month",
    teamSize: "Team Project",
    role: "Implemented computer vision algorithms, integrated detection logic, tested system performance, and optimized real-time processing.",
    challenges: [
      "Accurate eye detection under varying lighting conditions",
      "Reducing false alarms while maintaining sensitivity",
      "Maintaining real-time performance on limited hardware",
    ],
    achievements: [
      "Built a reliable driver safety monitoring system",
      "Achieved real-time fatigue detection with minimal latency",
      "Successfully tested across multiple lighting scenarios",
    ],
    futureScope: [
      "Mobile application for smartphone-based monitoring",
      "Cloud monitoring and fleet management integration",
      "Driver behavior analytics and reporting",
      "Integration with vehicle systems for automated alerts",
    ],
    awards: ["🥈 Second Prize — IoT Project Expo 2025, Saranathan College of Engineering"],
    featured: true,
    year: 2025,
  },
  {
    id: "fecs",
    slug: "fecs",
    title: "Forest Emergency Communication System",
    subtitle: "LoRa-Based Off-Grid Emergency Communication Network",
    category: "iot",
    problem:
    "Emergency responders working in forests and disaster zones often lose communication because of unavailable cellular networks, endangering lives and operations.",
    solution:
    "Designed an IoT-based communication system using LoRa mesh networking to enable long-range emergency communication without relying on existing network infrastructure.",
    features: [
      "Long-range LoRa communication (up to 2km+ range)",
      "GPS location sharing with real-time tracking",
      "Emergency SOS messaging with acknowledgement",
      "Mesh networking for extended coverage",
      "Real-time monitoring via web dashboard",
      "MQTT integration for data relay",
    ],
    architecture: "ESP32 Devices → LoRa SX1278 → Mesh Network → MQTT Gateway → React Dashboard",
    techStack: [
      { name: "ESP32", icon: "SiEspressif", category: "Hardware" },
      { name: "LoRa SX1278", icon: "SiSemtech", category: "Hardware" },
      { name: "React", icon: "FaReact", category: "Frontend" },
      { name: "Node.js", icon: "FaNodeJs", category: "Backend" },
      { name: "MQTT", icon: "SiMqtt", category: "Protocol" },
      { name: "GPS NEO-6M", icon: "SiGps", category: "Hardware" },
    ],
    screenshots: ["/images/projects/fecs/hero.png"],
    demoVideo: "",
    github: "https://github.com/Madhesh13-byte/fecs",
    liveDemo: "",
    duration: "2 Months",
    teamSize: "Team Project",
    role: "Designed communication architecture, integrated LoRa modules, implemented MQTT communication, and developed the monitoring dashboard.",
    challenges: [
      "Achieving reliable long-distance communication in forest environments",
      "Power optimization for battery-operated field devices",
      "Implementing robust mesh networking with dynamic routing",
    ],
    achievements: [
      "Successfully established communication in areas without cellular coverage",
      "Demonstrated reliable mesh networking with multiple nodes",
      "Built an end-to-end emergency communication prototype",
    ],
    futureScope: [
      "Satellite integration for global coverage",
      "AI-assisted emergency routing and prioritization",
      "End-to-end encrypted communication for security",
      "Mobile application for field responders",
    ],
    awards: ["Selected for Project Exhibition"],
    featured: true,
    year: 2025,
  },
  {
    id: "ai-software-studio",
    slug: "ai-software-studio",
    title: "AI Software Engineering Studio",
    subtitle: "Multi-Agent AI Platform for Autonomous Software Development",
    category: "software",
    problem:
    "Software development involves repetitive manual tasks such as requirement analysis, architecture design, backend generation, and documentation, reducing developer productivity.",
    solution:
    "Developed an autonomous AI platform that uses multiple specialized AI agents to automate different phases of the software development lifecycle, from requirement analysis to backend code generation.",
    features: [
      "Research Agent for automated information gathering",
      "Business Analyst Agent for requirement analysis",
      "Software Architect Agent for system design",
      "Database Design Agent for schema generation",
      "Backend Code Generator for API and logic generation",
      "Multi-Agent Workflow orchestration with Manager Agent",
      "Automatic documentation generation",
    ],
    architecture: "React Frontend → FastAPI Backend → Manager Agent → Specialized AI Agents → Ollama (Qwen2.5) → Generated Software Project",
    techStack: [
      { name: "React", icon: "FaReact", category: "Frontend" },
      { name: "FastAPI", icon: "SiFastapi", category: "Backend" },
      { name: "Python", icon: "FaPython", category: "Language" },
      { name: "Ollama", icon: "SiOllama", category: "AI" },
      { name: "Qwen2.5", icon: "SiQwen", category: "AI" },
      { name: "PostgreSQL", icon: "SiPostgresql", category: "Database" },
      { name: "REST APIs", icon: "SiRestapi", category: "Backend" },
    ],
    screenshots: ["/images/projects/ai-software-studio/hero.png"],
    demoVideo: "",
    github: "https://github.com/Nithish264033/AI_Engineering_studio",
    liveDemo: "",
    duration: "Ongoing",
    teamSize: "Solo Project",
    role: "Designed complete system architecture, developed AI agents, integrated Large Language Models, built APIs, and implemented frontend and backend.",
    challenges: [
      "AI agent orchestration and coordination",
      "Optimizing LLM response times for real-time interaction",
      "Managing inter-agent communication and state",
      "Scalable architecture design for multiple agents",
    ],
    achievements: [
      "Built a functional multi-agent AI platform for software automation",
      "Successfully orchestrated multiple specialized AI agents",
      "Enabled autonomous software development workflows",
    ],
    futureScope: [
      "Cloud deployment for public access",
      "Multi-model AI support for flexibility",
      "CI/CD integration for complete automation",
      "Enterprise project generation capabilities",
      "Plugin ecosystem for extensibility",
    ],
    awards: [],
    featured: true,
    year: 2026,
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
export const projectCategories = ["all", "ai", "iot", "fullstack", "software"] as const;